ament_prepend_unique_value GZ_SIM_RESOURCE_PATH "$AMENT_CURRENT_PREFIX/share"
ament_prepend_unique_value GZ_SIM_PLUGIn_PATH "$AMENT_CURRENT_PREFIX/lib/ur_description__"
ament_prepend_unique_value GZ_MODEL_PATH "$AMENT_CURRENT_PREFIX/share/ur_description__/meshes"
