  joint_1:
    has_velocity_limits: true
    max_velocity: 7.85
    has_acceleration_limits: true
    max_acceleration: 1.57
  joint_2:
    has_velocity_limits: true
    max_velocity: 6.63
    has_acceleration_limits: true
    max_acceleration: 1.326
  joint_3:
    has_velocity_limits: true
    max_velocity: 9.08
    has_acceleration_limits: true
    max_acceleration: 1.816
  joint_4:
    has_velocity_limits: true
    max_velocity: 9.6
    has_acceleration_limits: true
    max_acceleration: 1.92
  joint_5:
    has_velocity_limits: true
    max_velocity: 9.51
    has_acceleration_limits: true
    max_acceleration: 1.902
  joint_6:
    has_velocity_limits: true
    max_velocity: 17.45
    has_acceleration_limits: true
    max_acceleration: 3.49