controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
  
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    motoman_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    use_sim_time: true


joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

motoman_controller:
  ros__parameters:
    joints:
      - joint_s
      - joint_l
      - joint_e
      - joint_u
      - joint_r
      - joint_b
      - joint_t
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
