franka_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0025
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 5
gripper:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0025
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 5
franka_arm_gripper:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0025
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 5