ament_prepend_unique_value GZ_SIM_RESOURCE_PATH "$AMENT_CURRENT_PREFIX/share"
ament_prepend_unique_value GZ_SIM_PLUGIn_PATH "$AMENT_CURRENT_PREFIX/lib/motoman_description"
ament_prepend_unique_value GZ_MODEL_PATH "$AMENT_CURRENT_PREFIX/share/motoman_description/meshes"
