#
# Docker method.  Use pre-build ROS 2 docker image.
#
# Important Note, Docker Hub has restricted the number of image pull
# requests.
#
# See # https://docs.docker.com/docker-hub/download-rate-limit
#
# This means, if the you runs GitHub CI a lot, it will fail when you
# run more than 100 times within 6 hours.  And then, you will have to
# wait for a almost a day to be able to pull the docker image again.
#
# The alternative is to use GitHub Docker Registry or GitHub Pacakges
# (ghcr.io) instead of Docker Hub.
#
# https://www.youtube.com/watch?v=U7TY_qUD8yA&ab_channel=AndrewSchmelyun
# https://github.com/aschmelyun/github-actions-docker-phpunit
# https://github.com/aschmelyun/github-actions-docker-compile

name: Build (in Docker Container)
on: 
  # Triggered whenever push to the main branch
  push:
    branches: [ "test-docker" ]
    
  # Allow manual trigger
  workflow_dispatch:

jobs:
  my_build_job:
    name: Build and run unit test inside the ROS 2 Docker container
    runs-on: ubuntu-latest       # any ubuntu that has docker 
    defaults:
      run:
        shell: bash       # specify bash for use with docker container
    container:
      image: osrf/ros:rolling-desktop # use ROS Galactic from docker hub repository
    steps:
      - name: Install additional packages if needed
        run: |
          apt update
          apt install -y lcov
      - name: Check out the repo
        uses: actions/checkout@v3
        
      # Build for test coverage
      - name: Configure CMake flags and build exectables
        run: |
          cd aprs/ws
          source /opt/ros/rolling/setup.bash
          colcon build --cmake-args -DCOVERAGE=1
